server:
  port: 7777

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/skillup
    username: postgres
    password: root

  application:
    name: AuthService

jwt:
  secret: Bearer